"""migrations

Revision ID: 045fadf58bb4
Revises: 279d71ca1ab5
Create Date: 2023-08-06 21:47:35.556911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045fadf58bb4'
down_revision = '279d71ca1ab5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surveys', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'users', ['user_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'user_id')
    # ### end Alembic commands ###
