"""migrations

Revision ID: 0920cd68af12
Revises: 83a68cdde626
Create Date: 2023-08-08 05:34:15.344051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0920cd68af12'
down_revision = '83a68cdde626'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions_to_experts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions_to_experts', 'users', ['user_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions_to_experts', type_='foreignkey')
    op.drop_column('questions_to_experts', 'user_id')
    # ### end Alembic commands ###
