"""migrations

Revision ID: 1e78c5c70437
Revises: 61ce186273ca
Create Date: 2023-07-15 12:33:12.666675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e78c5c70437'
down_revision = '61ce186273ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('published_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'published_at')
    # ### end Alembic commands ###
