"""migrations

Revision ID: 6b5299d0fff8
Revises: 8a820ee3c6a3
Create Date: 2023-08-06 04:12:51.457357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5299d0fff8'
down_revision = '8a820ee3c6a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
