"""migrations

Revision ID: 7d1a16956f91
Revises: 6c0e6027a1c1
Create Date: 2023-07-15 08:24:44.400228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1a16956f91'
down_revision = '6c0e6027a1c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    op.drop_table('posts')
    op.add_column('post_comments', sa.Column('title', sa.String(), nullable=True))
    op.add_column('post_comments', sa.Column('content', sa.String(), nullable=True))
    op.add_column('post_comments', sa.Column('is_likeable', sa.Boolean(), nullable=True))
    op.add_column('post_comments', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_comments_title'), 'post_comments', ['title'], unique=False)
    op.create_foreign_key(None, 'post_comments', 'post_comments', ['post_id'], ['id'], ondelete='NO ACTION')
    op.drop_constraint('post_files_post_id_fkey', 'post_files', type_='foreignkey')
    op.create_foreign_key(None, 'post_files', 'post_comments', ['post_id'], ['id'], ondelete='NO ACTION')
    op.drop_constraint('post_likes_post_id_fkey', 'post_likes', type_='foreignkey')
    op.create_foreign_key(None, 'post_likes', 'post_comments', ['post_id'], ['id'], ondelete='NO ACTION')
    op.drop_column('post_likes', 'is_likeable')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_likes', sa.Column('is_likeable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.create_foreign_key('post_likes_post_id_fkey', 'post_likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_files', type_='foreignkey')
    op.create_foreign_key('post_files_post_id_fkey', 'post_files', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.drop_index(op.f('ix_post_comments_title'), table_name='post_comments')
    op.drop_column('post_comments', 'post_id')
    op.drop_column('post_comments', 'is_likeable')
    op.drop_column('post_comments', 'content')
    op.drop_column('post_comments', 'title')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='posts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='posts_pkey')
    )
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
