"""migrations

Revision ID: 83a68cdde626
Revises: c0c325f95740
Create Date: 2023-08-07 09:59:52.207682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a68cdde626'
down_revision = 'c0c325f95740'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'image_url')
    # ### end Alembic commands ###
