"""migrations

Revision ID: 84be5e4afa7c
Revises: 9d7951b5e16b
Create Date: 2023-07-29 17:18:30.869649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84be5e4afa7c'
down_revision = '9d7951b5e16b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('latitude', sa.Double(), nullable=True))
    op.create_index(op.f('ix_locations_latitude'), 'locations', ['latitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_latitude'), table_name='locations')
    op.drop_column('locations', 'latitude')
    # ### end Alembic commands ###
