"""migrations

Revision ID: 8a820ee3c6a3
Revises: 803555719606
Create Date: 2023-08-06 04:12:17.348215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a820ee3c6a3'
down_revision = '803555719606'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
