"""migrations

Revision ID: 979f09e6ba27
Revises: a030358c61dd
Create Date: 2023-07-29 18:46:14.432655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979f09e6ba27'
down_revision = 'a030358c61dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('name', sa.String(), nullable=True))
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.add_column('milk_banks', sa.Column('is_bank', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_milk_banks_is_bank'), 'milk_banks', ['is_bank'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_milk_banks_is_bank'), table_name='milk_banks')
    op.drop_column('milk_banks', 'is_bank')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_column('locations', 'name')
    # ### end Alembic commands ###
