"""migrations

Revision ID: 9f99161e19df
Revises: 84be5e4afa7c
Create Date: 2023-07-29 17:18:53.121356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f99161e19df'
down_revision = '84be5e4afa7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('longitude', sa.Double(), nullable=True))
    op.create_index(op.f('ix_locations_longitude'), 'locations', ['longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_longitude'), table_name='locations')
    op.drop_column('locations', 'longitude')
    # ### end Alembic commands ###
