"""migrations

Revision ID: b008ee530d74
Revises: 979f09e6ba27
Create Date: 2023-07-30 02:37:17.653603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b008ee530d74'
down_revision = '979f09e6ba27'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aprende_mas_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprende_mas_posts_id'), 'aprende_mas_posts', ['id'], unique=False)
    op.create_index(op.f('ix_aprende_mas_posts_title'), 'aprende_mas_posts', ['title'], unique=False)
    op.create_table('home_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_posts_id'), 'home_posts', ['id'], unique=False)
    op.create_index(op.f('ix_home_posts_title'), 'home_posts', ['title'], unique=False)
    op.drop_index('ix_post_home_id', table_name='post_home')
    op.drop_table('post_home')
    op.drop_index('ix_post_aprende_mas_id', table_name='post_aprende_mas')
    op.drop_table('post_aprende_mas')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_aprende_mas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_aprende_mas_pkey')
    )
    op.create_index('ix_post_aprende_mas_id', 'post_aprende_mas', ['id'], unique=False)
    op.create_table('post_home',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='post_home_pkey')
    )
    op.create_index('ix_post_home_id', 'post_home', ['id'], unique=False)
    op.drop_index(op.f('ix_home_posts_title'), table_name='home_posts')
    op.drop_index(op.f('ix_home_posts_id'), table_name='home_posts')
    op.drop_table('home_posts')
    op.drop_index(op.f('ix_aprende_mas_posts_title'), table_name='aprende_mas_posts')
    op.drop_index(op.f('ix_aprende_mas_posts_id'), table_name='aprende_mas_posts')
    op.drop_table('aprende_mas_posts')
    # ### end Alembic commands ###
