"""migrations

Revision ID: b78b241e92ff
Revises: 92ca9edd6e40
Create Date: 2023-07-31 01:21:00.233097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78b241e92ff'
down_revision = '92ca9edd6e40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_files_id', table_name='post_files')
    op.drop_table('post_files')
    op.drop_index('ix_questions_id', table_name='questions')
    op.drop_table('questions')
    op.add_column('post_comments', sa.Column('from_expert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post_comments', 'from_expert')
    op.create_table('questions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='questions_pkey')
    )
    op.create_index('ix_questions_id', 'questions', ['id'], unique=False)
    op.create_table('post_files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post_comments.id'], name='post_files_post_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='post_files_pkey')
    )
    op.create_index('ix_post_files_id', 'post_files', ['id'], unique=False)
    # ### end Alembic commands ###
