"""migrations

Revision ID: f6cc9de8ebb9
Revises: 6b5299d0fff8
Create Date: 2023-08-06 04:14:54.006994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6cc9de8ebb9'
down_revision = '6b5299d0fff8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_comments', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post_comments', 'post_categories', ['category_id'], ['id'], ondelete='NO ACTION')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    op.drop_column('post_comments', 'category_id')
    # ### end Alembic commands ###
